# Copyright (c) 2024-2025 Ziqi Fan
# Copyright (c) 2025 Shenzhen Yuejiang Technology Co., Ltd.
# SPDX-License-Identifier: Apache-2.0
# Modified by Dobot on 2025-12-1: design & configure parameters for Atom.

atom:
  dt: 0.002 # 500Hz
  inference_dt: 0.01 # 100Hz
  fixed_kp: [100.0, 100.0, 100.0, 100.0, 40.0, 40.0,
             100.0, 100.0, 100.0, 100.0, 40.0, 40.0,
             300.0, 
             150.0, 150.0, 150.0, 150.0, 120.0, 120.0, 120.0,
             150.0, 150.0, 150.0, 150.0, 120.0, 120.0, 120.0,
             40, 40]
  fixed_kd: [2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
             2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
             20.0,
             2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0,
             2.0, 2.0, 2.0, 2.0, 1.0, 1.0, 1.0,
             2.0, 2.0]
  
  torque_limits: [207.76, 241.42, 104.16, 213.80, 89.90, 89.90,
                  207.76, 241.42, 104.16, 213.80, 89.90, 89.90,
                  182.28,
                  93.0, 70.0, 70.0, 70.0, 34.0, 34.0, 34.0,
                  93.0, 70.0, 70.0, 70.0, 34.0, 34.0, 34.0,
                  12.0, 12.0]
  default_dof_pos: [-0.2, -0.01, 0.0, 0.4, -0.2, 0.0,
                    -0.2, -0.01, 0.0, 0.4, -0.2, 0.0,
                    0.0, 
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0]

  model_name: "atom.onnx"
  num_one_step_observations: 47
  num_history: 15
  clip_obs: 18.0
  clip_actions: 18.0

  rl_kp: [100, 95, 90, 110, 50, 50,
          100, 95, 90, 110, 50, 50,]

  rl_kd: [3.5, 2.5, 2.5, 3.5, 1.5, 1.5,
          3.5, 2.5, 2.5, 3.5, 1.5, 1.5,]
  
  num_of_dofs: 29
  num_of_policy_dofs: 12
  action_dim: 12 
  action_scale: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
                0.5, 0.5, 0.5, 0.5, 0.5, 0.5,]


  lin_vel_scale: 2.0
  ang_vel_scale: 1.0
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 1.0]

  max_speed_x: 0.6
  max_speed_y: 0.6
  max_yaw_rate: 0.8

  deadzone: 0.05